import movieCover from "../images/movie.jpg"

const demoMovies = [
    {
        id: "001",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "002",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "003",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "004",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "005",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "006",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "007",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Очень-очень длинное название фильма",
        nameEN: "Movie title",
    },
    {
        id: "008",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "009",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "010",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Длинное название фильма",
        nameEN: "Movie title",
    },
    {
        id: "011",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "012",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "013",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "014",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "015",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "016",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
]

const demoSavedMovies = [
    {
        id: "001",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "002",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
    {
        id: "003",
        duration: "90",
        image: movieCover,
        trailerLink: "#",
        nameRU: "Название фильма",
        nameEN: "Movie title",
    },
]

export {demoMovies, demoSavedMovies};